Year2013::Speakers = {
  'matt_aimonetti' => {
    name: 'Matt Aimonetti',
    image: 'matt',
    twitter: 'mattetti',
    github: 'mattetti',
    website: '',
    bio: 'Matt Aimonetti is an experienced technologist, entrepreneur, technical writer and active open-source contributor. Based in San Diego California, he currently works on his startup: Splice. Prior to Splice, Matt worked as a Tech manager/developer at LivingSocial, on video game development at Sony PlayStation and on many other things.',
    talk_title: 'Wicked Bad Ruby',
    talk_summary: 'Can you tell the difference between good and bad code? What do you base your judgment on?<br><br>Over the years, the Ruby community has built a fairly strong notion of &ldquo;the right way&rdquo; of writing code. During his thought provoking presentation, Matt will show that things are not simply good vs bad, and that what we call &ldquo;pretty&rdquo; code might, in fact, just be lipstick on a pig.',
    video: 'VO-NvnZfMA4',
    slides: '<script async class="speakerdeck-embed" data-id="f325aee016620131a63906e09cf22df5" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>'
  },
  'doug_alcorn' => {
    name: 'Doug Alcorn',
    image: 'alcorn',
    twitter: 'dougalcorn',
    github: 'dougalcorn',
    website: 'http://gaslight.co',
    bio: 'Doug is a partner with Gaslight in Cincinnati. He is a lover of ruby, spread sheets, and internet space ships.',
    talk_title: 'Market Analytics in EVE with Ruby',
    talk_summary: 'Ever wondered about market trading, analytics or algorithms but didn&rsquo;t want to lose your shirt experimenting? EVE Online is a Massively Multiplayer Online Role Playing Game (MMORPG) rich in data with a fully functional, player driven economy. Using some simple concepts and novel tools you can get access to this data and discover interesting I&rsquo;ll introduce you to market analytics and the cruel world of EVE Online.',
    video: 'pPNkgxv9isM',
    slides: ''
  },
  'joshua_ballanco' => {
    name: 'Joshua Ballanco',
    image: 'ballanco',
    twitter: 'manhattanmetric',
    github: 'jballanc',
    website: 'http://manhattanmetric.com',
    bio: 'Joshua has worked with Objective-C since 2002 and Ruby since 2004. He has built operating systems with Apple, local news websites with AOL, and somehow managed to finish a Ph.D. along the way. Currently, Joshua is Chief Scientist at Burnside Digital where he works with an amazing team of engineers and designers to solve problems for a wide range of clients. He works and lives in Ankara.',
    talk_title: 'RubyMotion: Under the Hood',
    talk_summary: 'By now you probably know that RubyMotion is a new toolchain that lets you use familiar Ruby techniques to develop applications for iOS&#133; but do you know what makes it tick? How is RubyMotion different from toolchains such as PhoneGap or Titanium? What does it mean to say that RubyMotion is implemented "on top of the Objective-C runtime"? And how the heck do I debug RubyMotion anyway?<br><br>I will attempt to answer these questions, and more, by looking deep into the underpinnings of RubyMotion. Along the way, I&rsquo;ll give a bit of an overview of the history of RubyMotion, and maybe even a glimpse at its future.',
    video: 'edVIJ60kIrQ',
    slides: '<iframe src="http://www.slideshare.net/slideshow/embed_code/27212781" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen> </iframe> <div style="margin-bottom:5px">'
  },
  'justin_campbell' => {
    name: 'Justin Campbell',
    image: 'campbell',
    twitter: 'justincampbell',
    github: 'justincampbell',
    website: 'http://justincampbell.me/',
    bio: 'Justin is a passionate Rubyist, hailing from the suburbs of Philadelphia. When he&rsquo;s not writing Ruby, he enjoys snowboarding and rock climbing with his wife, or playing StarCraft. Justin is also a budding programming-language geek.',
    talk_title: 'Hacking Your Home with Ruby',
    talk_summary: '15 years ago, Justin looked forward to the day when he could have a stack of expensive audio equipment with speakers in every room, lights that follow him around, and an intercom system so the family could page each other like Tim "The Tool Man" Taylor.<br><br>Ubiquitous networking, APIs for consumer electronics, and cheap computers like the Raspberry Pi have made it easier than ever to automate your home. We go over some popular technologies, see some code to glue it all together, and watch a live demo of some of Justin&rsquo;s favorite house hacks.',
    video: 'BeyTsdkItg4',
    slides: '<script async class="speakerdeck-embed" data-id="56a337701689013154fb4a6e1a634200" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>'
  },
  'joanne_cheng' => {
    name: 'Joanne Cheng',
    image: 'joanne',
    twitter: 'joannecheng',
    github: 'joannecheng',
    website: 'http://joannecheng.me/',
    bio: 'Joanne is a developer for thoughtbot, inc. in Denver, CO, happily writing code all day. When she&rsquo;s not writing code for thoughtbot, inc., she works on open source projects that benefit the state of Colorado and its citizens through <a class="section-info-link" href="http://codeforcommunities.org/" target="_blank">Code for Communities</a>. She was once a classical musician in training.',
    talk_title: 'Creativity with Ruby-Processing',
    talk_summary: 'Ruby-Processing is a simple wrapper for the Processing framework that combines the visual-driven environment of Processing with the fun of writing R we&rsquo;ll go through the ways to &ldquo;sketch&rdquo; with Ruby-Processing with several live coding examples and create something together. Through creativity, we can increase the breadth of problems we can solve in our day to day jobs.',
    video: 'Rnw9WNSph5k',
    slides: ''
  },
  'mike_desjardins' => {
    name: 'Mike Desjardins',
    image: 'desjardins',
    twitter: 'mdesjardins',
    github: 'mdesjardins',
    website: 'http://www.mikedesjardins.net',
    bio: 'Mike began programming on his Tandy 1000 when he was 13 years old and has never looked back. His first job out of college was writing assembly language firmware for disk drives, where his primary debugging tool was an oscilloscope. Today he&rsquo;s a Software Developer at Openbay, where he tinkers with Rails and Backbone, quietly disrupting the auto repair industry. When he&rsquo;s not at a keyboard, you can often find him geocaching with his family up in Portland, Maine.',
    talk_title: 'Rails Sojourn: One Man&rsquo;s Journey',
    talk_summary: 'With several spawling, monolithic Rails apps under my belt, I had the opportunity to go a different route. Bulging models, obtuse controllers, and views chock full of logic were my world. When I came up for air, all the cool kids were writing thick clients with svelte backends. Perhaps Sinatra and some hip Javascript framework were the way? Here&rsquo;s what I learned&hellip;',
    video: 'pyDd9xoGZCM',
    slides: '<iframe src="http://www.slideshare.net/slideshow/embed_code/27173830" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen> </iframe> <div style="margin-bottom:5px">'
  },
  'jason_garber' => {
    name: 'Jason Garber',
    image: 'garber',
    twitter: 'jasongarber',
    github: 'jgarber',
    website: 'http://jasongarber.com/ruby-developer',
    bio: 'Jason picked up Ruby while re-designing the Rosetta Stone website in 2005 and immediately fell in love with the language, the community, and open-source software. Later, he started committing to Why the Lucky Stiff&rsquo;s RedCloth repo and the next thing he knew, he was the owner, with a sketch from _why to prove it! Jason enjoys helping others level up their skills, through RailsGirls, Philly.rb, and corporate training. He is an engineer at PromptWorks, a Ruby shop in Philadelphia, where he enjoys pair programming with his co-founders, Greg and Mike.',
    talk_title: 'Writing DSLs with Parslet',
    talk_summary: 'Parslet makes it easy to write these kinds of DSLs in pure Ruby. In this talk you&rsquo;ll learn the basics, feel out the limitations of several approaches and find some common solutions. In no time, you&rsquo;ll have the power to make a great new DSL, slurp in obscure file formats, modify or fork other people&rsquo;s grammars (like Gherkin, TOML, or JSON), or even write your own programming language!',
    video: 'ET_POMJNWNs',
    slides: '<script async class="speakerdeck-embed" data-id="441b68c016a7013186827a1b357e9aaa" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>'
  },
  'nick_gauthier' => {
    name: 'Nick Gauthier',
    image: 'gauthier',
    twitter: 'ngauthier',
    github: 'ngauthier',
    website: 'http://ngauthier.com',
    bio: 'Nick Gauthier is a web freelancer focusing on Ruby on Rails and JavaScript. His experience spans from SQL to Sass and he always tests, all the time. He wrote Recipes with Backbone with Chris Strom and recently released his most recent eBook Mobile Web Patterns with Backbone.js. Aside from freelancing Nick runs &rsquo;More Awesome, a Baltimore-based web training organization, and he also co-founded Exobrain, an online mind-mapping tool.',
    talk_title: 'Outside-In Testing',
    talk_summary: 'As a freelancer I&rsquo;m often tasked with creating high quality web applications quickly while keeping the budget razor thin. In my experience, the absolute best bang-for-your-buck style of development has been BDD from the outside-in via acceptance tests. With acceptance tests you can quickly and accurately determine the minimum code necessary to fit the requirements of an application while achieving high code coverage and resilience to refactoring. By their very nature acceptance tests are the the simplest kinds of tests to write since they are expressed in the language of an end-user. In this talk we&rsquo;ll implement a feature from the outside-in, explaining the reasoning behind every step.',
    video: 'JDgOuKvRaf4',
    slides: '<a class="section-info-link" href="https://docs.google.com/presentation/d/1bbrR59IMNmudsI8cSeToQNwAHbxXV8HQxx0ExKX5lPQ/pub#slide=id.p" target="_blank">Slides</a>'
  },
  'steven_haddox' => {
    name: 'Steven Haddox',
    image: 'haddox',
    twitter: 'stevenhaddox',
    github: 'stevenhaddox',
    website: 'http://stevenhaddox.com',
    bio: 'Steven has over a decade of programming experience and has been a Ruby developer since 2008. His career consists of a wide-variety of development and production environments which have led him to create tools like <a href="https://github.com/stevenhaddox/rvm_fw" class="section-info-link" target="_blank">RVM::FW</a> to help ensure that development can be consistent in a multitude of circumstances.',
    talk_title: 'PEACE: Programming Expertly Amid Corporations &amp; Enterprises',
    talk_summary: 'Everyone casts the "Enterprise" as the most horrid place in the world to be a Ruby developer, and they used to be right. How does a Rubyist trying to stay current work in a confined and archaic environment with strict security restrictions? You do everything other Rubyists do, but you do it without sudo and from source. Together we&rsquo;ll identify the best open source self-hosted options for agile managment, provisioning, git hosting, error tracking, CI, isolated RVM, metrics, central logging, and security. As a bonus, you&rsquo;ll learn how to automate the setup of all these tools as much as possible without sudo privileges.',
    video: '3KfW10PxBpA',
    slides: '<a class="section-info-link" href="http://peace-in-the-enterprise.herokuapp.com/#/" target="_blank">Slides</a>'
  },
  'bryan_liles' => {
    name: 'Bryan Liles',
    image: 'bryan',
    twitter: 'bryanl',
    github: 'bryanl',
    website: '',
    bio: 'Based in Baltimore, Bryan Liles is the Senior Vice President of Thunderbolt Labs. Since 1993, Bryan has hacked into systems which he was then paid to protect; written more assembler than anyone should ever have to; worked with and against the government. Currently, Bryan is exploring the limits of Ruby and other trendy programming languages while building that next great product company. In his spare time, he trolls Twitter and grows miniature herb gardens.',
    talk_title: 'Machine Learning with Ruby',
    talk_summary: 'Not sure where to cluster or where to classify? Have you seen a linear regression lately? Every wanted to take a look into machine learning? Curious to what problems you can solve? Using Ruby to become familiar with machine learning and data-mining techniques is great way to get acclimated before diving in with both feet.',
    video: 'cO26TjhQWvA',
    slides: ''
  },
  'dan_mcclain' => {
    name: 'Dan McClain',
    image: 'dan',
    twitter: '_danmcclain',
    github: 'danmcclain',
    website: 'http://danmcclain.net',
    bio: 'I am the author of the postgre_ext gem, which adds ActiveRecord and Arel support for PostgreSQL datatypes, and contributed commits to Rails 4.0 that added PostgreSQL array support.',
    talk_title: 'Supercharging ActiveRecord with PostgreSQL',
    talk_summary: 'You&rsquo;ve been able to serialize Ruby objects with ActiveRecord in the past, but the database treats serialized objects as text. PostgreSQL has support for advanced data types, like arrays, hashes and ranges, natively, allowing the database to do the heavy work for you. You can query a table for records that contain an array with a specific element. You can build a reservation system in which the database makes sure that you don&rsquo;t double book a room. All of which happens in the database, preventing you from retrieving extra records and processing them in memory.<br><br>With Rails 4, ActiveRecord has been supercharged. The PostgreSQL adapter has been extended to support arrays and hashes, and was rewritten to make adding your own types easier than before. There are gems out there that allow you to leverage these datatypes in Rails 3 as well.',
    video: 'SiwuXtKLjIE',
    slides: '<iframe src="http://slid.es/danmcclain/supercharging-activerecord-with-postgresql/embed" width="576" height="420" scrolling="no" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
  },
  'christopher_meiklejohn' => {
    name: 'Christopher Meiklejohn',
    image: 'meiklejohn',
    twitter: 'cmeik',
    github: 'cmeiklejohn',
    website: '',
    bio: 'Christopher Meiklejohn is a Software Engineer with Basho Technologies, Inc. where he focuses on building rich web applications for Riak using Erlang and JavaScript. Before joining Basho, he worked at Swipely, a loyalty program startup based in Providence where he maintained critical infrastructure components written in Ruby. Christopher is also a graduate student in computer science at Brown University in Providence RI, where he studies formal verification and distributed systems.',
    talk_title: 'Bloom: A language for disorderly distributed programming',
    talk_summary: 'Traditional programming languages use a model of computation where individual instructions are executed in order. However, when building distributed systems this model fails to match the reality of how your application code is actually executed. Bloom is a language which allows programmers to build applications as a series of unordered statements while also providing facilities for imposing a particular ordering of events when necessary.<br><br>During this talk we will explore building applications in Bud, which is a prototype of Bloom implemented as a domain specific language in Ruby. We will discuss the concepts of logical monotonicity, disorderly collections, the CALM principle which is the root of the Bloom language, and how to use he Bloom language to identify critical sections of your code where a coordiation library should be used to ensure consistency.',
    video: '66bU45vVF00',
    slides: '<script async class="speakerdeck-embed" data-id="df54694016390131b4fc1af4385a3f14" data-ratio="1.2994923857868" src="//speakerdeck.com/assets/embed.js"></script>'
  },
  'mark_menard' => {
    name: 'Mark Menard',
    image: 'menard',
    twitter: 'mark_menard',
    github: 'MarkMenard',
    website: 'http://www.enablelabs.com/',
    bio: 'Mark Menard is the founder of Enable Labs, a boutique consulting firm, in Troy, NY, specializing in product development, business productivity and problem solving. Mark used to be a Java developer and caught the dynamic language bug when he started coding in Groovy and then discovered Ruby and Rails. Mark spends most of his free time with his wife Sylva and their two sons Ezra and Avi.',
    talk_title: 'JRuby: Insights from Six Years in Production',
    talk_summary: 'JRuby is the primary alternative implementation of Ruby available. With support for native threads, excellent garbage collection, and the introduction of Invoke Dynamic it has grown into a formidable platform. So, what can JRuby do for you? Learn how JRuby differs from MRI, how JRuby supports parallelism, how to use Java libraries from JRuby, how to use Ruby from Java and more. Java no longer means just the language anymore, the JVM is an excellent place to host Ruby applications.',
    video: 't_JJD-AEtNM',
    slides: '<iframe src="http://www.slideshare.net/slideshow/embed_code/28177149" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen> </iframe> <div style="margin-bottom:5px">'
  },
  'sandi_metz' => {
    name: 'Sandi Metz',
    image: 'sandi',
    twitter: 'sandimetz',
    github: 'skmetz',
    website: 'http://sandimetz.com/',
    bio: 'Sandi Metz has thirty years of experience working on projects that survived to grow and change; her book <a href="http://poodr.com" class="section-info-link" target="_blank">&ldquo;Practical Object-Oriented Design in Ruby&rdquo;</a> is an outgrowth of this experience. Dealing with long lived applications has left her deeply biased towards practical solutions that produce working software that is easy to change. She believes in simple code and straightforward explanations.<br><br>Sandi worked for many years at Duke University and now independently consults and teaches. She lives in Durham, North Carolina, where her daily bicycle commute now consists of a loop that starts and ends at her house.',
    talk_title: 'Sandi Metz Tells Your Future',
    talk_summary: '',
    video: 'fhpT6Pc4AqM',
    slides: '<script async class="speakerdeck-embed" data-id="b9425fc0d2cb01304d1c5647665b10a6" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>'
  },
  'mike_nicholaides' => {
    name: 'Mike Nicholaides',
    image: 'nicholaides',
    twitter: 'nicholaides',
    github: 'nicholaides',
    website: 'http://ablegray.com/',
    bio: 'By day, Mike Nicholaides is a co-founder and Ruby/JavaScript consultant at PromptWorks, the premier Ruby shop in Philadelphia. But when the sun goes down&#133; he does, too, because having kids is exhausting!<br><br>Between dawn and dusk Mike can be found feeding his addiction to learning. In addition to technology, his interests include all things language, business, ancient and prehistory, and religion.<br><br>When he&rsquo;s not coding, spending time with his family, or reading, you&rsquo;ll probably find him organizing local JavaScript and coworking meetups and throwing Philadelphia&rsquo;s annual Code Retreat.',
    talk_title: 'Securing Your Rails App',
    talk_summary: 'How can you know if your Rails app is safe? With potential vulnerabilities lurking in your app&rsquo;s code, in gems you depend on, in services you use, and in the Rails source itself, attackers have myriad vectors to gain access to your data, interrupt your service, and damage your reputation.<br><br>I&rsquo;ll cover the basics of securing your Rails app, evaluating and mitigating the risk inherent in live web applications, and strategies for keeping your app secure as new threats emerge.',
    video: 'Jv5Y2bLYeik',
    slides: '<script async class="speakerdeck-embed" data-id="1547f1e02e9c0131dc8066d07d2effc2" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>'
  },
  'foy_savas' => {
    name: 'Foy Savas',
    image: 'foy',
    twitter: 'foysavas',
    github: 'foysavas',
    website: 'http://www.foysavas.com/',
    bio: 'Foy is a long time Rubyist now working as a venture capitalist at <a href="http://alphaprime.vc/" class="section-info-link" target="_blank">AlphaPrime Ventures</a>. Having previously worked as a tech consultant, Foy now gets his kicks by helping portfolio companies roadmap projects and strategize implementation. Come to think of it, the only difference from his consulting days is that the startups stopped paying him and started taking his money.',
    talk_title: 'Closing Keynote',
    talk_summary: '',
    video: '65_Qy3anbMw',
    slides: ''
  },
  'richard_schneeman' => {
    name: 'Richard Schneeman',
    image: 'schneeman',
    twitter: 'schneems',
    github: 'schneems',
    website: 'http://schneems.com/',
    bio: 'Richard writes Ruby at Heroku at teaches Rails at the University of Texas. When he isn&rsquo;t obsessively compulsively playing Starcraft 2 he writes such gems as <a href="https://github.com/schneems/wicked" class="section-info-link" target="_blank">Wicked</a>, <a href="https://github.com/schneems/sextant" class="section-info-link" target="_blank">Sextant</a>, <a href="https://github.com/opro/opro" class="section-info-link" target="_blank">oPro</a>. He&rsquo;s on the Rails issue team, and wants you to sign up for <a href="http://www.codetriage.com/" class="section-info-link" target="_blank">Code Triage</a>. Before working as a programmer &ndash; Richard graduated from Space camp where he prototyped a perpetual motion machine that didn&rsquo;t work, and from Scout camp where he built trebuchets that did.',
    talk_title: 'Dissecting Ruby with Ruby',
    talk_summary: 'Underneath the beautiful veneer of our Ruby libraries lies a twisted tangle of writhing guts. Maybe you&rsquo;re curious how the pieces fit together or maybe you&rsquo;re tracking down a bug, either way it&rsquo;s easy to get lost in the blood and bile that ties our code together. In this talk you&rsquo;ll learn how to use simple and sharp Ruby tools to slice into large libraries with surgical precision. Turn your impossible bugs into pull requests, and level up your programming skills by Dissecting Ruby with Ruby.',
    video: 'UYVUSoNrM-c',
    slides: '<script async class="speakerdeck-embed" data-id="593ae26076340130492822000a1e820e" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>'
  },
  'loren_segal' => {
    name: 'Loren Segal',
    image: 'loren',
    twitter: 'lsegal',
    github: 'lsegal',
    website: '',
    bio: 'Loren Segal is an SDKs and Tools developer at Amazon Web Services working on the AWS SDKs for Ruby and Node.js. In his spare time, Loren also likes to hack on open source libraries and tools like YARD, a Ruby documentation tool, RubyCorrect, a static analysis and automatic test case generation tool, and Seahorse, a web service API modeling library.',
    talk_title: 'Towards Tooling; A Look at What is Missing From Our Toolbox',
    talk_summary: 'You can usually judge the maturity of a programming language ecosystem by the breadth of its tooling. For example, Java has a plethora of IDEs that each, in turn, have many well maintained refactoring and code quality plugins (like FindBugs and PMD). C/C++ is equally well established in this space. Even JavaScript is becoming well represented, with a number of static code analyzers and language supersets (like Dart and TypeScript) aimed at improving tooling in the language. But where is Ruby in all of this? This talk will shed some light on the existing tools available in the Ruby world as well as some new tools just starting to be built out in the areas of static analysis, formal verification, and code quality checking. We will look at what kind of tools the Ruby community is good at building, what kind of tools we are bad at, and most of all, some of the tooling we should be working on to really improve our ecosystem and drive more developers to this wonderful language.',
    video: 'wPu2kVI09Yc',
    slides: '<iframe src="http://www.slideshare.net/slideshow/embed_code/28048354" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC;border-width:1px 1px 0;margin-bottom:5px" allowfullscreen> </iframe> <div style="margin-bottom:5px">'
  },
  'dan_sharp' => {
    name: 'Dan Sharp',
    image: 'sharp',
    twitter: '',
    github: '',
    website: 'http://www.linkedin.com/in/mrdrsharp',
    bio: 'Dan is a life-long geek, having been fascinated with computers since early childhood. He cut his teeth, like many, on Java and PHP, but found Ruby via Ruby on Rails in 2005... building one of the first successful Rails-based SaaS ventures&#133; and never looking back. These days, Dan works as Senior Software Architect with the Nexia&#153; team at Ingersoll Rand, affording him the luxury of a startup environment backed by a multi-billion dollar company. He resides in Golden, CO with his wife and two children. When not hacking code, he&rsquo;s usually lost in the back country somewhere, enjoying the great outdoors.',
    talk_title: 'Killing Fibonacci',
    talk_summary: 'Testing is an important part of the development lifecycle of any software solution. It is particularly important in the Ruby community with lots of real and perceived pressure to test first, test often and test fully (or at least 90% coverage, right?). However, there has not been as much focus on the why of testing as a mechanism to encourage good code practices, good design decisions and coverage that is meaningful. This presentation aims to change all that. I will start with a brief overview of ruby testing: the why, what, how, when and where. For the rest of the presentation, I will take the Fibonnaci sequence and deconstruct it via a tongue-in-cheek approach to showcase why Good Testing&#153; is so much more important than Testing&#133; and why tests should force the developer to think deeper about their code&#133; not just as implementation but as behavior!<br><br>(The killing of Fibonacci will take place live. However no animals or Italian mathematicians will be harmed during the talk.)',
    video: 'gzfObLKICdg',
    slides: ''
  },
  'neeraj_singh' => {
    name: 'Neeraj Singh',
    image: 'singh',
    twitter: 'neerajdotname',
    github: 'neerajdotname',
    website: 'http://bigbinary.com/neeraj',
    bio: 'Neeraj loves ruby, JavaScript and open source culture. He has contributed to open source projects like RubyOnRails, jQuery-ujs, Spree and ActiveMerchant . He is based in Miami and runs BigBinary, a RubyOnRails consulting firm.',
    talk_title: 'ActiveRecord is still magical',
    talk_summary: 'ActiveRecord is complex code and because of complexity it has edge cases. In fact lots of edge cases. We will take a look at a number of ActiveRecord features to see how it works and how to deal with some of the edge cases.<br><br>We will see how default_scope works. And why method "unscoped" removes default_scope from models but not from associations.<br><br>Do you know the difference between CollectionProxy and Relation ? Do you know why in a has_many through case "@physician.patients.create!" would work but "@physician.patients.where(active: true).create! would silently fail without creating the association record?<br><br>We will discuss why while patching Active Record you should run your tests against all three databases.<br><br>Guess which of these two obey :destroy option: @customer.orders.delete(@order) or @customer.orders.destroy(@order).<br><br>In Rails 3 when where conditions are merged then the last where condition wins. In Rails 4 all the where conditions are &lsquo;And&rsquo;ed. But not defautl_scope. We will see how and why.<br><br>Will also discuss implementation detail of features like inverse_of, autosave and callbacks.',
    video: 'RUOvI_iMyDY',
    slides: '<script async class="speakerdeck-embed" data-id="3909c200157f013102e61a54756b74c2" data-ratio="1.2994923857868" src="//speakerdeck.com/assets/embed.js"></script>'
  },
  'mark_sobkowicz' => {
    name: 'Mark Sobkowicz',
    image: 'sobkowicz',
    twitter: 'MarkSobkowicz',
    github: 'sobko',
    website: 'http://www.27classrooms.com/',
    bio: 'Mark Sobkowicz has been teaching physics and programming at Lincoln Sudbury Regional High School since 1995, and started using Ruby (and Rails) in 2007. He has taught students programming using Logo, Java, RealBasic, Objective C, and Ruby. He lives in Maynard, MA and spends as much time as he can in the White Mountains of New Hampshire, where he worked for the Appalachian Mountain Club when he was a younger man.',
    talk_title: 'Ruby: The Next Generation',
    talk_summary: 'Introducing programming to young people is a balancing act. What language to use? Bore the quickest students, or leave some behind?  Teach them style, or let them discover their own? At Lincoln Sudbury Regional High School, Ruby has helped us bring our Intro to Programming course to a new sweet spot, where students leave the one semester course with a bit of knowledge and a lot of enthusiasm, filling our upper level programming courses and learning more on their own.<br><br>As Rubyists we often pride ourselves on our elegant, terse, clever code. When we teach our students, we keep it simple. Simple conditionals, simple loops and iterators. This allows us to get more quickly to a place where students can express their creativity. And thats what gets them hooked.',
    video: 'tX07sT7Cr6Y',
    slides: '<a class="section-info-link" href="http://s3.amazonaws.com/27Teach/materials/docs/9/original/Wicked_Good_Talk.pdf?1381690919" target="_blank">PDF Slides</a>'
  },
  'charlie_somerville' => {
    name: 'Charlie Somerville',
    image: 'charlie',
    twitter: 'charliesome',
    github: 'charliesome',
    website: '',
    bio: 'Charlie is a passionate Rubyist from Melbourne, Australia. When he&rsquo;s not slinging C and Ruby for GitHub, he&rsquo;s relaxing by sitting back on the couch hacking on MRI with a cup of coffee by his side.',
    talk_title: 'MRI Magic Tricks',
    talk_summary: 'Like any other software, MRI has bugs. In this talk, Charlie will dive deep into the internals of MRI and demonstrate how a few interesting bugs can be leveraged to do crazy things you never thought were possible in Ruby.',
    video: 'SBdqCYKWISU',
    slides: '<a class="section-info-link" href="https://charlie.bz/files/mri-magic-tricks.pdf" target="_blank">PDF Slides</a>'
  },
  'seth_vargo' => {
    name: 'Seth Vargo',
    image: 'vargo',
    twitter: 'sethvargo',
    github: 'sethvargo',
    website: 'http://sethvargo.com/',
    bio: 'Seth is a long-time Ruby developer who landed in operations as a Solutions Engineer at Opscode. While his degree is in Information Systems from Carnegie Mellon, Seth specializes in Ruby development and system administration. But most importantly, Seth is incredibly lazy, which is why automation and DRY are two principles that are practiced in his daily life. An author or core contributor to projects such as fauxhai, chefspec, berkshelf, bootstrap_forms, powify, and more, Seth believes in the power of the open source and community.',
    talk_title: 'Using Ruby to Automate Your Life',
    talk_summary: 'You probably use Ruby everyday, so why not use Ruby to automate some common tasks? What if you could spin up an EC2 instance and have it automatically configure your web server, database, users, and more? What if you could effectively capture and replicate your production environments reliably and consistently? What if you could then give developers production-like environments as Virtual Machines, with no additional work? What if you could set up your new laptop with multiple Ruby versions, your favorite software, and even change the desktop background - from a single command? The good news is - you can!<br><br>Chef is a configuration management and automation tool that solves these problems and many m you&rsquo;ll learn common just how easy it is to capture your infrastructure in Chef. Save time and money by using Chef&rsquo;s Ruby DSL to "define" your laptop.<br><br>How many times have you bought a new laptop and realize just how much stuff you installed over the years? If you&rsquo;re using Chef, run a single command and all your favorite Applications, Preferences, and even passwords are back in place. And the best part - because Chef is written in Ruby, you get to continue using the language you love!',
    video: 'oTOBWbA-M6s',
    slides: '<script async class="speakerdeck-embed" data-id="6eacd9b016450131b4fd1af4385a3f14" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>'
  },
  'jon_yurek' => {
    name: 'Jon Yurek',
    image: 'yurek',
    twitter: 'jyurek',
    github: 'jyurek',
    website: 'http://thoughtbot.com/',
    bio: 'Jon Yurek is a founder of thoughtbot. He spends his days trying to reach vim enlightenment and writing code solely to make his tests pass. Ever since he played with BASIC on his Apple IIe, he knew programming was for him. The rest of his time is spent camping and playing European-style board games.',
    talk_title: 'Naming is Hard!',
    talk_summary: 'Coming up with a good name is one of the hardest things to do in programming. It&rsquo;s one of the least technical things we do, but it has one of the largest impacts on how understandable our code is. Ruby is a very expressive language, which makes it very suitable to naming things well and thereby making maintenance easier. This talk will go over more than just how to name variables and classes: it will show how to extract and name concepts, processes, and procedures from existing code in order to understand it better.',
    video: 'UDixUZWLo_U',
    slides: '<a class="section-info-link" href="https://github.com/jyurek/naming-is-hard" target="_blank">Slides on GitHub</a>'
  }
}
